server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://server:5000/api/;
        proxy_set_header Host $host;
    }

    location /uploads/ {
        proxy_pass http://server:5000/uploads/;
    }

    location /raw-images/ {
        proxy_pass http://server:5000/raw-images/;
    }
}