import uuid
from datetime import datetime

from sqlalchemy import Column, String, DateTime, Float, ForeignKey
from app.db_types import GUID
from sqlalchemy.orm import relationship

from app.database import Base


class BiodiversityAssessment(Base):
    """
    A computed snapshot of biodiversity / ecosystem health for a monitoring
    site, generated by the Biodiversity Intelligence Engine (Milestone 2)
    and the Wildlife Health Scoring Engine (Milestone 3).
    """
    __tablename__ = "biodiversity_assessments"

    id = Column(GUID(), primary_key=True, default=uuid.uuid4)
    monitoring_site_id = Column(GUID(), ForeignKey("monitoring_sites.id"), nullable=False)

    # Core biodiversity metrics
    species_richness = Column(Float, default=0.0)          # number of distinct species observed
    shannon_diversity_index = Column(Float, default=0.0)   # species diversity index
    simpson_diversity_index = Column(Float, default=0.0)

    # Weighted ecosystem health score inputs (see Weighted Scoring Model in spec)
    species_diversity_score = Column(Float, default=0.0)     # 30%
    population_stability_score = Column(Float, default=0.0)  # 25%
    habitat_quality_score = Column(Float, default=0.0)       # 20%
    endangered_species_score = Column(Float, default=0.0)    # 15%
    environmental_conditions_score = Column(Float, default=0.0)  # 10%

    overall_ecosystem_health_score = Column(Float, default=0.0)
    conservation_status_label = Column(String(50), default="unknown")  # Excellent..Critical

    assessed_at = Column(DateTime, default=datetime.utcnow)

    monitoring_site = relationship("MonitoringSite")
