import enum
import uuid
from datetime import datetime

from sqlalchemy import Column, String, DateTime, Enum, ForeignKey, Text
from app.db_types import GUID
from sqlalchemy.orm import relationship

from app.database import Base


class RecommendationPriority(str, enum.Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class RecommendationCategory(str, enum.Enum):
    PATROL_ALLOCATION = "patrol_allocation"
    HABITAT_RESTORATION = "habitat_restoration"
    ENDANGERED_SPECIES_PROTECTION = "endangered_species_protection"
    MONITORING_OPTIMIZATION = "monitoring_optimization"
    RESOURCE_ALLOCATION = "resource_allocation"


class ConservationRecommendation(Base):
    """
    Conservation Recommendation Engine output (Milestone 3, spec section 9).

    Generated by a rule-based engine (app/services/conservation_engine.py)
    that reads the outputs of the Biodiversity, Population, and Habitat
    Intelligence Engines and produces prioritized, actionable
    recommendations. This is intentionally rule-based rather than a trained
    ML model - conservation recommendation logic benefits from being
    auditable and explainable to forest department staff, not a black box.
    """
    __tablename__ = "conservation_recommendations"

    id = Column(GUID(), primary_key=True, default=uuid.uuid4)
    monitoring_site_id = Column(GUID(), ForeignKey("monitoring_sites.id"), nullable=False)

    priority = Column(Enum(RecommendationPriority), default=RecommendationPriority.MEDIUM)
    category = Column(Enum(RecommendationCategory), nullable=False)
    title = Column(String(200), nullable=False)
    description = Column(Text, nullable=False)
    rationale = Column(Text, nullable=True)  # why the engine generated this - keeps it auditable

    is_resolved = Column(String(20), default="open")  # open | in_progress | resolved
    generated_at = Column(DateTime, default=datetime.utcnow)

    monitoring_site = relationship("MonitoringSite")
