"""
Conservation Recommendation Engine (Milestone 3)
----------------------------------------------------
Generates rule-based conservation recommendations by reading the outputs
of the Ecosystem Health, Habitat Intelligence, and Population Estimation
engines already built. Each rule below maps directly to a real signal in
the data — nothing here is generated by a language model or guessed.
"""
from typing import Optional

from sqlalchemy.orm import Session

from app.services.ecosystem_health_service import calculate_ecosystem_health
from app.services.habitat_service import calculate_habitat_intelligence
from app.services.population_service import calculate_population_estimates


def generate_recommendations(
    db: Session,
    researcher_id: Optional[str] = None,
):
    ecosystem = calculate_ecosystem_health(db, researcher_id)
    habitat = calculate_habitat_intelligence(db, researcher_id)
    population = calculate_population_estimates(db, researcher_id=researcher_id)

    recommendations = []

    # --- Rule 1: Overall ecosystem health ---
    if ecosystem["overall_score"] < 50:
        recommendations.append({
            "priority": "High",
            "category": "Ecosystem Health",
            "recommendation": (
                f"Overall ecosystem health score is {ecosystem['overall_score']} "
                f"({ecosystem['status']}). Immediate review of monitoring coverage "
                "and conservation resource allocation is recommended."
            ),
        })
    elif ecosystem["overall_score"] < 65:
        recommendations.append({
            "priority": "Medium",
            "category": "Ecosystem Health",
            "recommendation": (
                f"Ecosystem health is at {ecosystem['overall_score']} "
                f"({ecosystem['status']}). Continue monitoring; consider targeted "
                "surveys in lower-scoring sites."
            ),
        })

    # --- Rule 2: Endangered species detections ---
    if ecosystem["endangered_detections"] > 0:
        ratio = ecosystem["endangered_detections"] / max(ecosystem["total_detections"], 1)
        priority = "High" if ratio > 0.15 else "Medium"
        recommendations.append({
            "priority": priority,
            "category": "Species Protection",
            "recommendation": (
                f"{ecosystem['endangered_detections']} endangered-species detection"
                f"{'s' if ecosystem['endangered_detections'] != 1 else ''} recorded "
                f"({round(ratio * 100, 1)}% of all detections). Recommend increased "
                "patrol frequency and anti-poaching measures at the affected sites."
            ),
        })

    # --- Rule 3: Per-site habitat quality ---
    for site in habitat["sites"]:
        if site["status"] == "Critical":
            recommendations.append({
                "priority": "High",
                "category": "Habitat Restoration",
                "recommendation": (
                    f"'{site['site_name']}' is in Critical habitat condition "
                    f"(score {site['habitat_health_score']}). Recommend on-site "
                    "habitat assessment and restoration planning."
                ),
            })
        elif site["status"] == "Vulnerable":
            recommendations.append({
                "priority": "Medium",
                "category": "Habitat Restoration",
                "recommendation": (
                    f"'{site['site_name']}' shows Vulnerable habitat signs "
                    f"(score {site['habitat_health_score']}). Recommend closer "
                    "monitoring and preventive intervention."
                ),
            })

    # --- Rule 4: Sites with very low observation activity ---
    for site in habitat["sites"]:
        if site["total_observations"] < 3:
            recommendations.append({
                "priority": "Low",
                "category": "Monitoring Optimization",
                "recommendation": (
                    f"'{site['site_name']}' has only {site['total_observations']} "
                    "logged observation(s). Recommend increasing monitoring "
                    "frequency (additional camera traps or audio sensors) at this site."
                ),
            })

    # --- Rule 5: Declining species populations ---
    declining_species = [
        s for s in population["species_population"] if s["trend"] == "decreasing"
    ]
    for species in declining_species:
        recommendations.append({
            "priority": "High",
            "category": "Population Protection",
            "recommendation": (
                f"'{species['species_name']}' population trend is decreasing "
                f"(recent: {species['recent_period_count']}, prior: "
                f"{species['prior_period_count']}). Recommend investigating "
                "causes (habitat loss, poaching, disease) and increasing survey frequency."
            ),
        })

    # --- Rule 6: Low overall species richness (single-species dominance risk) ---
    if ecosystem["factors"]["species_diversity"]["score"] < 30 and population["species_count"] > 0:
        recommendations.append({
            "priority": "Medium",
            "category": "Biodiversity",
            "recommendation": (
                "Low species diversity detected across monitored sites. Recommend "
                "expanding survey scope to capture a broader range of taxa and "
                "verify no under-monitored habitat types are being missed."
            ),
        })

    # If nothing triggered any rule, everything is healthy — say so explicitly
    if not recommendations:
        recommendations.append({
            "priority": "Info",
            "category": "General",
            "recommendation": (
                "No conservation concerns detected in current data. Continue "
                "regular monitoring to maintain baseline coverage."
            ),
        })

    priority_order = {"High": 0, "Medium": 1, "Low": 2, "Info": 3}
    recommendations.sort(key=lambda r: priority_order.get(r["priority"], 99))

    return {
        "ecosystem_score": ecosystem["overall_score"],
        "ecosystem_status": ecosystem["status"],
        "recommendation_count": len(recommendations),
        "recommendations": recommendations,
    }