services:
  db:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_USER: wildlife_admin
      POSTGRES_PASSWORD: wildlife_pass
      POSTGRES_DB: wildlife_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    environment:
      DATABASE_URL: postgresql://wildlife_admin:wildlife_pass@db:5432/wildlife_db
      SECRET_KEY: change-this-to-something-random-later
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata: